### ISSUE TITLE
where is the requirements.txt

### ISSUE THREAD

**Issue by Plus-Ultar** [Loahit5101/PointPillars-Camera-LiDAR-Fusion#1]
hello , sorry to borther you, i want to know where the requirements.txt is ? Thank you for telling me!!

**Comment by Loahit5101** [comment]
Hi, thank you for your interest! I have updated the requirements for the Pointpillars Network. I am still working on the fusion module and will be updating the requirements for it soon.

**Comment by Plus-Ultar** [comment]
Thank you for what you have done ! i am really interested in this project!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Loahit5101/PointPillars-Camera-LiDAR-Fusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月12日(星期四) 凌晨5:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Loahit5101/PointPillars-Camera-LiDAR-Fusion] where is the requirements.txt (Issue #1)





 
Hi, thank you for your interest! I have updated the requirements for the Pointpillars Network. I am still working on the fusion module and will be updating the requirements for it soon.
